# Generated by Django 3.2.12 on 2022-04-30 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TcmVideoClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='中药名称')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '中药视频类别表',
                'verbose_name_plural': '中药视频类别表',
                'db_table': 'tcm_video_classification',
            },
        ),
        migrations.CreateModel(
            name='TcmVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='视频名称')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('file', models.FileField(max_length=255, upload_to='', verbose_name='视频')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='封面')),
                ('status', models.CharField(blank=True, choices=[('0', '发布中'), ('1', '未发布')], max_length=1, null=True, verbose_name='状态')),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.tcmvideoclassification', verbose_name='类别')),
            ],
            options={
                'verbose_name': '中药视频表',
                'verbose_name_plural': '中药视频表',
                'db_table': 'tcm_video',
            },
        ),
    ]
