# Generated by Django 3.2.12 on 2022-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcmvideoclassification',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '启用'), ('1', '不启用')], max_length=1, null=True, verbose_name='状态'),
        ),
    ]
