# Generated by Django 3.2.12 on 2022-04-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_tcmvideoclassification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcmvideoclassification',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='中药类别名称'),
        ),
    ]
