# Generated by Django 3.2.12 on 2022-04-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_tcmvideoclassification_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcmvideo',
            options={'verbose_name': '中药视频', 'verbose_name_plural': '中药视频'},
        ),
        migrations.AlterField(
            model_name='tcmvideoclassification',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '启用'), ('0', '不启用')], default=1, max_length=1, null=True, verbose_name='状态'),
        ),
    ]
