# Generated by Django 3.2.12 on 2022-05-01 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0005_auto_20220430_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcmvideo',
            name='collected',
            field=models.ManyToManyField(blank=True, related_name='collected_videos', to=settings.AUTH_USER_MODEL, verbose_name='收藏的用户'),
        ),
        migrations.AddField(
            model_name='tcmvideo',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL, verbose_name='喜欢的用户'),
        ),
        migrations.AddField(
            model_name='tcmvideo',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='观看次数'),
        ),
        migrations.AlterField(
            model_name='tcmvideo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='tcmvideo',
            name='file',
            field=models.FileField(max_length=255, upload_to='video', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='tcmvideo',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '发布中'), ('0', '未发布')], max_length=1, null=True, verbose_name='状态'),
        ),
    ]
