# Generated by Django 3.2.12 on 2022-05-02 08:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20220501_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcmvideo',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
    ]
