# Generated by Django 3.2.12 on 2022-05-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_tcmvideo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcmvideo',
            name='collected',
        ),
        migrations.RemoveField(
            model_name='tcmvideo',
            name='liked',
        ),
    ]
