# Generated by Django 3.2.12 on 2022-05-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20220512_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcmvideo',
            name='collected',
        ),
        migrations.RemoveField(
            model_name='tcmvideo',
            name='liked',
        ),
    ]
