# Generated by Django 3.2.12 on 2022-05-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_alter_tcmvideo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcmvideo',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='video.tcmvideoclassification', verbose_name='类别'),
        ),
    ]
