# Generated by Django 3.2.12 on 2022-05-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_alter_tcmvideo_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcmvideo',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tcmvideo',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '发布中'), ('0', '未发布')], default=0, max_length=1, null=True, verbose_name='状态'),
        ),
    ]
