# Generated by Django 3.2.12 on 2022-05-02 14:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('tcm_title', models.CharField(blank=1, max_length=128, null=1, verbose_name='中药名称')),
                ('tcm_banner', models.ImageField(blank=True, null=True, upload_to='tcm_banner', verbose_name='轮播图')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
                'db_table': 'tcm_banner',
            },
        ),
        migrations.CreateModel(
            name='CheseHerbsShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('tcm_title', models.CharField(max_length=255, null=1, verbose_name='中药名称')),
                ('tcm_show', models.ImageField(blank=True, null=True, upload_to='tcm_banner', verbose_name='展示图')),
            ],
            options={
                'verbose_name': '首页展示',
                'verbose_name_plural': '首页展示',
                'db_table': 'tcm_herb_show',
            },
        ),
        migrations.CreateModel(
            name='TcmDetailInfomations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('tcm_title', models.CharField(blank=1, max_length=128, null=1, verbose_name='中药名称')),
                ('scientific_name', models.CharField(blank=1, max_length=128, null=1, verbose_name='学名')),
                ('alias', models.CharField(max_length=128, verbose_name='别名')),
                ('family_name', models.CharField(max_length=128, verbose_name='科名')),
                ('detail_desc', tinymce.models.HTMLField(blank=1, null=1, verbose_name='详细介绍')),
                ('efficacy_function', models.CharField(blank=1, max_length=255, null=1, verbose_name='功效作用')),
                ('efficacy_category', models.CharField(blank=1, max_length=255, null=1, verbose_name='功效类别')),
                ('forum_on_tcm', models.CharField(blank=1, max_length=255, null=1, verbose_name='升降浮沉')),
                ('channel_entry', models.CharField(blank=1, max_length=255, null=1, verbose_name='归经')),
                ('five_tastes', models.CharField(blank=1, max_length=255, null=1, verbose_name='五味')),
                ('toxicity_of', models.CharField(blank=1, max_length=255, null=1, verbose_name='毒性')),
                ('source', models.CharField(blank=1, max_length=255, null=1, verbose_name='来源')),
                ('four_gas', models.CharField(blank=1, choices=[('0', '寒性'), ('1', '热性'), ('2', '温性'), ('3', '凉性'), ('4', '平性')], max_length=2, null=1, verbose_name='四气')),
                ('medicinal', models.CharField(blank=1, max_length=255, null=1, verbose_name='药性')),
                ('medicinal_part', models.CharField(blank=1, max_length=255, null=1, verbose_name='药用部分')),
                ('view_count', models.IntegerField(blank=True, default=0, verbose_name='浏览次数')),
                ('banner', models.OneToOneField(null=1, on_delete=django.db.models.deletion.CASCADE, to='tcm_query.banner', verbose_name='轮播图')),
                ('chese_herb_show', models.OneToOneField(null=1, on_delete=django.db.models.deletion.CASCADE, to='tcm_query.cheseherbsshow', verbose_name='首页展示信息')),
            ],
            options={
                'verbose_name': '详细中药介绍',
                'verbose_name_plural': '详细中药介绍',
                'db_table': 'tcm_detail_info',
            },
        ),
        migrations.CreateModel(
            name='TcmPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('tcm_title', models.CharField(blank=1, max_length=255, null=1, verbose_name='图片名称')),
                ('image', models.ImageField(upload_to='tcm_pic', verbose_name='中药图片')),
                ('tcm_detail_info', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='tcm_query.tcmdetailinfomations', verbose_name='详细中药信息')),
            ],
            options={
                'verbose_name': '中药图片',
                'verbose_name_plural': '中药图片',
                'db_table': 'tcm_pic',
            },
        ),
    ]
