# Generated by Django 3.2.12 on 2022-05-03 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcm_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='alias',
            field=models.CharField(blank=1, max_length=128, null=1, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='banner',
            field=models.OneToOneField(blank=1, null=1, on_delete=django.db.models.deletion.CASCADE, to='tcm_query.banner', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='chese_herb_show',
            field=models.OneToOneField(blank=1, null=1, on_delete=django.db.models.deletion.CASCADE, to='tcm_query.cheseherbsshow', verbose_name='首页展示信息'),
        ),
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='efficacy_category',
            field=models.TextField(blank=1, max_length=255, null=1, verbose_name='功效类别'),
        ),
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='efficacy_function',
            field=models.TextField(blank=1, null=1, verbose_name='功效作用'),
        ),
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='family_name',
            field=models.CharField(blank=1, max_length=128, null=1, verbose_name='科名'),
        ),
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='four_gas',
            field=models.CharField(blank=1, max_length=2, null=1, verbose_name='四气'),
        ),
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='medicinal',
            field=models.TextField(blank=1, max_length=255, null=1, verbose_name='药性'),
        ),
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='medicinal_part',
            field=models.TextField(blank=1, null=1, verbose_name='药用部分'),
        ),
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='source',
            field=models.TextField(blank=1, max_length=255, null=1, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='tcm_title',
            field=models.CharField(blank=1, db_index=1, max_length=128, null=1, verbose_name='中药名称'),
        ),
    ]
