# Generated by Django 3.2.12 on 2022-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcm_query', '0002_auto_20220503_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheseherbsshow',
            name='is_show',
            field=models.CharField(blank=1, choices=[('1', '展示'), ('0', '不展示')], default=0, max_length=4, null=1, verbose_name='是否展示'),
            preserve_default=1,
        ),
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='four_gas',
            field=models.CharField(blank=1, max_length=125, null=1, verbose_name='四气'),
        ),
    ]
