# Generated by Django 3.2.12 on 2022-05-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcm_query', '0003_auto_20220504_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcmdetailinfomations',
            name='medicinal_part_ca',
            field=models.CharField(blank=1, choices=[('0', '全草'), ('1', '叶类'), ('2', '花'), ('3', '果实、种子'), ('4', '根、根茎'), ('5', '树皮、根皮')], max_length=20, null=1, verbose_name='药用部位类别'),
            preserve_default=1,
        ),
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='medicinal_part',
            field=models.TextField(blank=1, null=1, verbose_name='药用部位'),
        ),
    ]
