# Generated by Django 3.2.12 on 2022-05-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcm_query', '0004_auto_20220509_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='medicinal_part',
            field=models.TextField(blank=1, null=1, verbose_name='药物性状'),
        ),
    ]
