# Generated by Django 3.2.12 on 2022-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcm_query', '0005_alter_tcmdetailinfomations_medicinal_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_show',
            field=models.CharField(blank=1, choices=[('1', '展示'), ('0', '不展示')], default=0, max_length=4, null=1, verbose_name='是否展示'),
            preserve_default=1,
        ),
    ]
