# Generated by Django 3.2.12 on 2022-05-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcm_query', '0006_banner_is_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcmdetailinfomations',
            name='chese_herb_show',
        ),
        migrations.AddField(
            model_name='cheseherbsshow',
            name='tcm_detail',
            field=models.OneToOneField(blank=1, null=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tcm_query.tcmdetailinfomations', verbose_name='中药信息'),
            preserve_default=1,
        ),
    ]
