# Generated by Django 3.2.12 on 2022-05-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcm_query', '0007_auto_20220515_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheseherbsshow',
            name='tcm_detail',
        ),
        migrations.AddField(
            model_name='tcmdetailinfomations',
            name='chese_herb_show',
            field=models.OneToOneField(blank=1, null=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tcm_query.cheseherbsshow', verbose_name='展示图'),
            preserve_default=1,
        ),
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='banner',
            field=models.OneToOneField(blank=1, null=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tcm_query.banner', verbose_name='轮播图'),
        ),
    ]
