# Generated by Django 3.2.12 on 2022-05-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcm_query', '0008_auto_20220515_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcmdetailinfomations',
            name='alias',
            field=models.CharField(blank=1, max_length=255, null=1, verbose_name='别名'),
        ),
    ]
